baseURL = "/CivicTechLab/"
fullURL = "//www.codeforportland.org/CivicTechLab/"
languageCode = "en-US"
defaultContentLanguage = "en"
paginate = 50
theme = "sublime"
title = "Civic Tech Lab"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Code4PDX Infrastructure Engineering"
	description = "Facilitating the ability to code and contribute."
	copyright = "Code4PDX"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Infrastructure Engineering"
	bio = "Code4PDX"
	bio2 = "Portland, OR 97223"
	subscribe = "Subscribe"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Rex@CodeForPortland.org"
		url = "mailto:rex@codeforportland.org"
